{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rails-k8s-helm.serviceAccountName" . }}
  labels:
{{ include "rails-k8s-helm.labels" . | nindent 4 }}
{{- end -}}
